### ISSUE TITLE
Failed to allocate instance of opencc

### ISSUE THREAD

**Issue by UlyssesZh** [songjiz/opencc-rb#2]
```ruby
require 'opencc'
OpenCC.t2s '測試'
```
```plain
/home/ulysses/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/opencc-rb-1.0.6/lib/opencc.rb:25:in `initialize': (opencc_open) failed to allocate instance of opencc (Exception)
	from /home/ulysses/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/opencc-rb-1.0.6/lib/opencc.rb:25:in `new'
	from /home/ulysses/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/opencc-rb-1.0.6/lib/opencc.rb:25:in `block (2 levels) in singleton class'
	from (irb):2:in `<main>'
	from /home/ulysses/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/irb-1.11.0/exe/irb:9:in `<top (required)>'
	from /home/ulysses/.local/share/rtx/installs/ruby/3.2.2/bin/irb:25:in `load'
	from /home/ulysses/.local/share/rtx/installs/ruby/3.2.2/bin/irb:25:in `<main>'
```
- Ruby 3.2.2
- opencc-rb 1.0.6
- OpenCC 1.1.1

**Comment by songjiz** [comment]
I apologize for the delay in my response. Based on your description, I tested locally with Ruby 3.2.2 and 3.3.0, and everything worked fine. Could you provide more details?

Here are some possible steps to troubleshoot:

1. Operating System: Confirm which operating system you are using (e.g., Windows, macOS, or Linux).
2. Ruby Version Manager: You mentioned Ruby 3.2.2, but make sure you’re using a Ruby version manager (e.g., RVM, rbenv, or asdf).

Thanks!

**Comment by songjiz** [comment]
I used the mise(formerly known as rtx) as version manager, and everything worked fine.

- step 1

  ```sh
  mise current
  ```
  output
  ```
  ruby 3.2.2
  ```
- step 2

  ```sh
  which gem
  ```
  output
  ```
  .local/share/mise/installs/ruby/3.2.2/bin/gem
  ``` 
  
  ```sh
  which irb
  ```
  output
  ```
  .local/share/mise/installs/ruby/3.2.2/bin/irb
  ```
- step 3

  ```sh
  gem install opencc-rb
  ```
  output
  ```
  Building native extensions. This could take a while...
  Successfully installed opencc-rb-1.0.6
  Parsing documentation for opencc-rb-1.0.6
  Installing ri documentation for opencc-rb-1.0.6
  Done installing documentation for opencc-rb after 0 seconds
  1 gem installed
  ```
- step 4

  ```sh
  irb
  irb(main):001:0> require 'opencc'
  irb(main):002:0> OpenCC.t2s '測試'
  => "测试"
  ```

**Comment by UlyssesZh** [comment]
I originally got this error on Ubuntu. Now I already deleted that OS.

I tried just now with Arch Linux and NixOS, but I cannot reproduce the bug now. I am closing this issue.
